trips_db = []
catches_db = []
species_db = [
    {"id": 1, "name": "Largemouth Bass", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/largemouth-bass.png"},
    {"id": 2, "name": "Smallmouth Bass", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/smallmouth-bass.png"},
    {"id": 3, "name": "Spotted Bass", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/spotted-bass.png"},
    {"id": 4, "name": "Bluegill", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/bluegill.png"},
    {"id": 5, "name": "Redear Sunfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/redear-sunfish.png"},
    {"id": 6, "name": "Pumpkinseed Sunfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pumpkinseed-sunfish.png"},
    {"id": 7, "name": "Green Sunfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/green-sunfish.png"},
    {"id": 8, "name": "Crappie (Black)", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/black-crappie.png"},
    {"id": 9, "name": "Crappie (White)", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/white-crappie.png"},
    {"id": 10, "name": "Walleye", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/walleye.png"},
    {"id": 11, "name": "Sauger", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/sauger.png"},
    {"id": 12, "name": "Northern Pike", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/northern-pike.png"},
    {"id": 13, "name": "Muskellunge", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/muskellunge.png"},
    {"id": 14, "name": "Chain Pickerel", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/chain-pickerel.png"},
    {"id": 15, "name": "Yellow Perch", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/yellow-perch.png"},
    {"id": 16, "name": "White Perch", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/white-perch.png"},
    {"id": 17, "name": "Channel Catfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/channel-catfish.png"},
    {"id": 18, "name": "Blue Catfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/blue-catfish.png"},
    {"id": 19, "name": "Flathead Catfish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/flathead-catfish.png"},
    {"id": 20, "name": "Common Carp", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/common-carp.png"},
    {"id": 21, "name": "Grass Carp", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/grass-carp.png"},
    {"id": 22, "name": "Rainbow Trout", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/rainbow-trout.png"},
    {"id": 23, "name": "Brown Trout", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/brown-trout.png"},
    {"id": 24, "name": "Brook Trout", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/brook-trout.png"},
    {"id": 25, "name": "Lake Trout", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/lake-trout.png"},
    {"id": 26, "name": "Chinook Salmon", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/chinook-salmon.png"},
    {"id": 27, "name": "Coho Salmon", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/coho-salmon.png"},
    {"id": 28, "name": "Sockeye Salmon", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/sockeye-salmon.png"},
    {"id": 29, "name": "Pink Salmon", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pink-salmon.png"},
    {"id": 30, "name": "Chum Salmon", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/chum-salmon.png"},
    {"id": 31, "name": "Whitefish", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/whitefish.png"},
    {"id": 32, "name": "Burbot", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/burbot.png"},
    {"id": 33, "name": "Freshwater Drum", "waterType": "Freshwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/freshwater-drum.png"},
    {"id": 34, "name": "Striped Bass", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/striped-bass.png"},
    {"id": 35, "name": "Bluefish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/bluefish.png"},
    {"id": 36, "name": "Pacific Halibut", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pacific-halibut.png"},
    {"id": 37, "name": "California Halibut", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/california-halibut.png"},
    {"id": 38, "name": "Atlantic Halibut", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/atlantic-halibut.png"},
    {"id": 39, "name": "Canary Rockfish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/canary-rockfish.png"},
    {"id": 40, "name": "Lingcod", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/lingcod.png"},
    {"id": 41, "name": "Cabezon", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/cabezon.png"},
    {"id": 42, "name": "Pacific Mackerel", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pacific-mackerel.png"},
    {"id": 43, "name": "Spanish Mackerel", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/spanish-mackerel.png"},
    {"id": 44, "name": "King Mackerel", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/king-mackerel.png"},
    {"id": 45, "name": "Yellowtail Amberjack", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/yellowtail-amberjack.png"},
    {"id": 46, "name": "Amberjack", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/amberjack.png"},
    {"id": 47, "name": "Pacific Barracuda", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pacific-barracuda.png"},
    {"id": 48, "name": "Great Barracuda", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/great-barracuda.png"},
    {"id": 49, "name": "Yellowfin Tuna", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/yellowfin-tuna.png"},
    {"id": 50, "name": "Bluefin Tuna", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/bluefin-tuna.png"},
    {"id": 51, "name": "Albacore Tuna", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/albacore-tuna.png"},
    {"id": 52, "name": "Skipjack Tuna", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/skipjack-tuna.png"},
    {"id": 53, "name": "Mahi Mahi", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/mahi-mahi.png"},
    {"id": 54, "name": "Wahoo", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/wahoo.png"},
    {"id": 55, "name": "Red Snapper", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/red-snapper.png"},
    {"id": 56, "name": "Vermilion Snapper", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/vermilion-snapper.png"},
    {"id": 57, "name": "Pacific Cod", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pacific-cod.png"},
    {"id": 58, "name": "Atlantic Cod", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/atlantic-cod.png"},
    {"id": 59, "name": "Haddock", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/haddock.png"},
    {"id": 60, "name": "Alaska Pollock", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/alaska-pollock.png"},
    {"id": 61, "name": "Sheepshead", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/sheepshead.png"},
    {"id": 62, "name": "Black Drum", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/black-drum.png"},
    {"id": 63, "name": "Red Drum", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/red-drum.png"},
    {"id": 64, "name": "Pacific Sanddab", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/pacific-sanddab.png"},
    {"id": 65, "name": "Summer Flounder", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/summer-flounder.png"},
    {"id": 66, "name": "English Sole", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/english-sole.png"},
    {"id": 67, "name": "Leopard Shark", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/leopard-shark.png"},
    {"id": 68, "name": "Spiny Dogfish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/spiny-dogfish.png"},
    {"id": 69, "name": "Widow Rockfish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/widow-rockfish.png"},
    {"id": 70, "name": "Yelloweye Rockfish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/yelloweye-rockfish.png"},
    {"id": 71, "name": "Yellowtail Rockfish", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/yellowtail-rockfish.png"},
    {"id": 72, "name": "Bigeye Tuna", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/bigeye-tuna.png"},
    {"id": 73, "name": "Atlantic Pollock", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/atlantic-pollock.png"},
    {"id": 74, "name": "Winter Flounder", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/winter-flounder.png"},
    {"id": 75, "name": "Dover Sole", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/dover-sole.png"},
    {"id": 76, "name": "Petrale Sole", "waterType": "Saltwater", "region": "North America", "image": "http://localhost.com:8000/static/images/species/petrale-sole.png"},
]
