trips_db = []
catches_db = []
species_db = [
    {"id": 1, "name": "Albacore Tuna", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/albacore-tuna.png", "isFavorite": False},
    {"id": 2, "name": "Barred Sand Bass", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 3, "name": "Barred Surfperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/barred-surfperch.png", "isFavorite": False},
    {"id": 4, "name": "Bat Ray", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 5, "name": "Bigeye Tuna", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bigeye-tuna.png", "isFavorite": False},
    {"id": 6, "name": "Black Croaker", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 7, "name": "Black Perch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 8, "name": "Black Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 9, "name": "Black Sea Bass", "region": ["Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/black-sea-bass.png", "isFavorite": False},
    {"id": 10, "name": "Black-and-Yellow Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 11, "name": "Blacksmith", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 12, "name": "Blue Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 13, "name": "Blue Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 14, "name": "Bocaccio Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 15, "name": "Broadnose Sevengill Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 16, "name": "Brown Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 17, "name": "Brown Smoothhound Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 18, "name": "Cabezon", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/cabezon.png", "isFavorite": False},
    {"id": 19, "name": "Calico Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 20, "name": "Calico Surfperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 21, "name": "California Corbina", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/corbina.png", "isFavorite": False},
    {"id": 22, "name": "California Grunion", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/grunion.png", "isFavorite": False},
    {"id": 23, "name": "California Halibut", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/california-halibut.png", "isFavorite": False},
    {"id": 24, "name": "California Moray Eel", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 25, "name": "California Mussel", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 26, "name": "California Scorpionfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 27, "name": "California Sheephead", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/sheepshead.png", "isFavorite": False},
    {"id": 28, "name": "California Spiny Lobster", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 29, "name": "California Two-Spot Octopus", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 30, "name": "Canary Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/canary-rockfish.png", "isFavorite": False},
    {"id": 31, "name": "Chilipepper Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 32, "name": "China Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 33, "name": "Chinook Salmon", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 34, "name": "Coho Salmon", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 35, "name": "Common Thresher Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 36, "name": "Copper Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 37, "name": "Cowcod", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 38, "name": "Diamond Trubot", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 39, "name": "Dungeness Crab", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 40, "name": "Flag Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 41, "name": "Garibaldi", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 42, "name": "Giant Red Sea Cucumber", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 43, "name": "Gopher Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 44, "name": "Grass Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 45, "name": "Greenblotched Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 46, "name": "Greenspotted Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 47, "name": "Greenstriped Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 48, "name": "Halfbanded Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 49, "name": "Halfmoon", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 50, "name": "Horn Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 51, "name": "Jacksmelt", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 52, "name": "Kellet's Whelk", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 53, "name": "Kelp Bass", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/kelp-bass.png", "isFavorite": False},
    {"id": 54, "name": "Kelp Greenling", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 55, "name": "Kelp Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 56, "name": "Leopard Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/leopard-shark.png", "isFavorite": False},
    {"id": 57, "name": "Lingcod", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/lingcod.png", "isFavorite": False},
    {"id": 58, "name": "Mahi Mahi", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/mahi-mahi.png", "isFavorite": False},
    {"id": 59, "name": "Market Squid", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 60, "name": "Monkeyface Prickleback", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 61, "name": "Night Smelt", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 62, "name": "Northern Anchovy", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/northern-anchovy.png", "isFavorite": False},
    {"id": 63, "name": "Ocean Pink Shrimp", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 64, "name": "Ocean Whitefish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 65, "name": "Olive Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 66, "name": "Opah", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/opah.png", "isFavorite": False},
    {"id": 67, "name": "Opaleye", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 68, "name": "Pacific Angel Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 69, "name": "Pacific Barracuda", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-barracuda.png", "isFavorite": False},
    {"id": 70, "name": "Pacific Blue Marlin", "region": ["South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-blue-marlin.png", "isFavorite": False},
    {"id": 71, "name": "Pacific Bluefin Tuna", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefin-tuna.png", "isFavorite": False},
    {"id": 72, "name": "Pacific Bonito", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bonito.png", "isFavorite": False},
    {"id": 73, "name": "Pacific Butterfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 74, "name": "Pacific Cod", "region": ["North Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-cod.png", "isFavorite": False},
    {"id": 75, "name": "Pacific Gaper Clam", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 76, "name": "Pacific Geoduck Clam", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 77, "name": "Pacific Hagfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 78, "name": "Pacific Halibut", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-halibut.png", "isFavorite": False},
    {"id": 79, "name": "Pacific Herring", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-herring.png", "isFavorite": False},
    {"id": 80, "name": "Pacific Mackerel", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-mackerel.png", "isFavorite": False},
    {"id": 81, "name": "Pacific Razor Clam", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 82, "name": "Pacific Sanddab", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-sanddab.png", "isFavorite": False},
    {"id": 83, "name": "Pacific Sardine", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/pacific-sardine.png", "isFavorite": False},
    {"id": 84, "name": "Pacific Spiny Dogfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/spiny-dogfish.png", "isFavorite": False},
    {"id": 85, "name": "Pacific Whiting", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 86, "name": "Pile Perch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 87, "name": "Pismo Clam", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 88, "name": "Queenfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 89, "name": "Quillback Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 90, "name": "Rainbow Seaperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 91, "name": "Red Sea Urchin", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 92, "name": "Redstripe Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 93, "name": "Redtail Surfperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 94, "name": "Ridgeback Prawn", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 95, "name": "Rock Crab", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 96, "name": "Rock Greenling", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 97, "name": "Rock Wrasse", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 98, "name": "Rosethorn Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 99, "name": "Rosy Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 100, "name": "Round Stingray", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 101, "name": "Rubberlip Seaperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 102, "name": "Sablefish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/sablefish.png", "isFavorite": False},
    {"id": 103, "name": "Salmon Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 104, "name": "Sand Sole", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/dover-sole.png", "isFavorite": False},
    {"id": 105, "name": "Sargo", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 106, "name": "Señorita", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 107, "name": "Sheep Crab", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 108, "name": "Shiner Perch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 109, "name": "Shortfin Mako Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 110, "name": "Shovelnose Guitarfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/shovelnose-sturgeon.png", "isFavorite": False},
    {"id": 111, "name": "Silver Surfperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 112, "name": "Skipjack Tuna", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/skipjack-tuna.png", "isFavorite": False},
    {"id": 113, "name": "Slender Crab", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 114, "name": "Smallhead Flyingfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 115, "name": "Soupfin Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 116, "name": "Jack Mackerel", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/spanish-mackerel.png", "isFavorite": False},
    {"id": 117, "name": "Speckled Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 118, "name": "Spot Prawn", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 119, "name": "Spotfin Croaker", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 120, "name": "Spotted Sand Bass", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 121, "name": "Squarespot Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 122, "name": "Starry Flounder", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/winter-flounder.png", "isFavorite": False},
    {"id": 123, "name": "Starry Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 124, "name": "Striped Bass", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/striped-bass.png", "isFavorite": False},
    {"id": 125, "name": "Striped Marlin", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/striped-marlin.png", "isFavorite": False},
    {"id": 126, "name": "Striped Seaperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 127, "name": "Stripetail Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 128, "name": "Surf Smelt", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 129, "name": "Swell Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 130, "name": "Swordfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/swordfish.png", "isFavorite": False},
    {"id": 131, "name": "Thornback", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 132, "name": "Tiger Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 133, "name": "Topsmelt", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 134, "name": "Treefish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/bluefish.png", "isFavorite": False},
    {"id": 135, "name": "Vermilion Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/vermilion-snapper.png", "isFavorite": False},
    {"id": 136, "name": "Wahoo", "region": ["South Coast"], "image": "http://localhost.com:8000/static/images/species/wahoo.png", "isFavorite": False},
    {"id": 137, "name": "Walleye Surfperch", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/redtail-surfperch.png", "isFavorite": False},
    {"id": 138, "name": "Warty Sea Cucumber", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 139, "name": "Washington Clam", "region": ["Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 139, "name": "Butter Clam", "region": ["North Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 140, "name": "White Croaker", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 141, "name": "White Seabass", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-sea-bass.png", "isFavorite": False},
    {"id": 142, "name": "White Shark", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 143, "name": "White Sturgeon", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-sturgeon.png", "isFavorite": False},
    {"id": 144, "name": "Widow Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/red-snapper.png", "isFavorite": False},
    {"id": 145, "name": "Wolf Eel", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 146, "name": "Yelloweye Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/yelloweye-rockfish.png", "isFavorite": False},
    {"id": 147, "name": "Yellowfin Croaker", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/white-hake.png", "isFavorite": False},
    {"id": 148, "name": "Yellowfin Tuna", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/yellowfin-tuna.png", "isFavorite": False},
    {"id": 149, "name": "Yellowtail Jack", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/yellowtail-amberjack.png", "isFavorite": False},
    {"id": 150, "name": "Yellowtail Rockfish", "region": ["North Coast", "Central Coast", "South Coast"], "image": "http://localhost.com:8000/static/images/species/yellowtail-rockfish.png", "isFavorite": False},
]
