trips_db = []
catches_db = []
species_db = [
    {"id": 1, "name": "Largemouth Bass", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 2, "name": "Smallmouth Bass", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 3, "name": "Spotted Bass", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 4, "name": "Bluegill", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 5, "name": "Redear Sunfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 6, "name": "Pumpkinseed Sunfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 7, "name": "Green Sunfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 8, "name": "Crappie (Black)", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 9, "name": "Crappie (White)", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 10, "name": "Walleye", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 11, "name": "Sauger", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 12, "name": "Northern Pike", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 13, "name": "Muskellunge", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 14, "name": "Chain Pickerel", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 15, "name": "Yellow Perch", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 16, "name": "White Perch", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 17, "name": "Channel Catfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 18, "name": "Blue Catfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 19, "name": "Flathead Catfish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 20, "name": "Common Carp", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 21, "name": "Grass Carp", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 22, "name": "Rainbow Trout", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 23, "name": "Brown Trout", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 24, "name": "Brook Trout", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 25, "name": "Lake Trout", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 26, "name": "Chinook Salmon", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 27, "name": "Coho Salmon", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 28, "name": "Sockeye Salmon", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 29, "name": "Pink Salmon", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 30, "name": "Chum Salmon", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 31, "name": "Whitefish", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 32, "name": "Burbot", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 33, "name": "Freshwater Drum", "waterType": "Freshwater", "region": "North America", "image": ""},
    {"id": 34, "name": "Striped Bass", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 35, "name": "Bluefish", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 36, "name": "Pacific Halibut", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 37, "name": "California Halibut", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 38, "name": "Atlantic Halibut", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 39, "name": "Pacific Rockfish", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 40, "name": "Lingcod", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 41, "name": "Cabezon", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 42, "name": "Pacific Mackerel", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 43, "name": "Spanish Mackerel", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 44, "name": "King Mackerel", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 45, "name": "Yellowtail Amberjack", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 46, "name": "Amberjack", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 47, "name": "Pacific Barracuda", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 48, "name": "Great Barracuda", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 49, "name": "Yellowfin Tuna", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 50, "name": "Bluefin Tuna", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 51, "name": "Albacore Tuna", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 52, "name": "Skipjack Tuna", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 53, "name": "Dolphinfish (Mahi-Mahi)", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 54, "name": "Wahoo", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 55, "name": "Red Snapper", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 56, "name": "Vermilion Snapper", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 57, "name": "Pacific Cod", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 58, "name": "Atlantic Cod", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 59, "name": "Haddock", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 60, "name": "Pollock", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 61, "name": "Sheepshead", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 62, "name": "Black Drum", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 63, "name": "Red Drum", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 64, "name": "Pacific Sanddab", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 65, "name": "Flounder", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 66, "name": "Sole", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 67, "name": "Leopard Shark", "waterType": "Saltwater", "region": "North America", "image": ""},
    {"id": 68, "name": "Spiny Dogfish", "waterType": "Saltwater", "region": "North America", "image": ""},
]
